# Project identification
sonar.projectKey=Kafka-Example
sonar.projectName=Kafka Example
sonar.projectVersion=1.0.0

# Source configuration
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes

# Encoding
sonar.sourceEncoding=UTF-8

# Test & coverage reports
sonar.junit.reportPaths=target/surefire-reports
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Exclusions
sonar.exclusions=**/config/**,**/dto/**,**/*Application.java
sonar.test.exclusions=**/*IT.java
